---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: employee
  labels:
    app: employee  

spec: 
  replicas: 1     
  template: 
    metadata: 
      labels:
        app: employee 
    spec:                       # <- The correct place for the 'spec' field
      containers:
      - name: employee 
        image: radhakant/employeems 
        ports:
        - containerPort: 8080

        env:
        - name: DB_HOST
          value: mysqldb 
        - name: DB_NAME
          value: emp5 
        - name: DB_USERNAME 
          value: root
        - name: DB_PASSWORD 
          value: root
        - name: SPRING_PROFILES_ACTIVE 
          value: k8s
      restartPolicy: Always    
  selector:
    matchLabels:
      app: employee 
  

---
apiVersion: v1 
kind: Service 
metadata: 
  name: employee
spec:
  type: NodePort
  selector:
    app: employee
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002   # Correct capitalization is 'nodePort'
...
