---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: department
  labels:
    app: department

spec: 
  replicas: 1    
  template: 
    metadata: 
      name: department
      labels:
        app: department
    spec:                       # <- The correct place for the 'spec' field
      containers:
      - name: department
        image: radhakant/departmentms 
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

        env:
        - name: DB_HOST
          value: mysqldb 
        - name: DB_NAME
          value: emp5 
        - name: DB_USERNAME 
          value: root
        - name: DB_PASSWORD 
          value: root
        - name: SPRING_PROFILES_ACTIVE 
          value: k8s
      restartPolicy: Always    
  selector:
    matchLabels:
      app: department    

---
apiVersion: v1 
kind: Service 
metadata: 
  name: department
spec:
  type: NodePort
  selector:
    app: department 
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30001   # Correct capitalization is 'nodePort'
...
